Default: &defaults
  database: gymmemo.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: gymmemo_test.sqlite3
  <<: *defaults

Staging:
  database: gymmemo_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: gymmemo_production.sqlite3
  poolsize: 100
  <<: *defaults
